# Generated by Django 4.2.6 on 2024-03-26 06:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Banks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='Bank',
            new_name='bank',
        ),
        migrations.AlterField(
            model_name='bank',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_banks', to=settings.AUTH_USER_MODEL),
        ),
    ]
